version: 0.2

phases:
  install:
    commands:
      - echo "Install phase - no dependencies"
      - chmod +x scripts/*.sh

  build:
    commands:
      - echo "Build phase completed"

artifacts:
  files:
    - '**/*'
